spring:
    application:
        name: carp
    profiles:
        # The commented value for `active` can be replaced with valid spring profiles toManufacture load.
        # Otherwise, it will be filled in by gradle when building the WAR file
        # Either way, it can be overridden by `--spring.profiles.active` value passed in the commandline or `-Dspring.profiles.active` set in `JAVA_OPTS`
        active: dev
    jackson:
        serialization.write_dates_as_timestamps: false
    jpa:
        open-in-view: false
    messages:
        basename: i18n/messages
    http:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: HTML
        cache: false
        suffix: .html
        encoding: UTF-8
    datasource:
      sqlScriptEncoding: UTF-8