spring:
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://10.10.30.42:5432/aggt?useUnicode=true&characterEncoding=utf8&
        username: carp
        password: JimBom05@
        hikari:
          data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true
          sql-script-encoding: UTF-8
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: postgresql
        show-sql: false
        properties:
            hibernate.connection.CharSet: utf8
            hibernate.connection.characterEncoding: utf8
            hibernate.jdbc.lob.non_contextual_creation: true
        hibernate:
            ddl-auto: none
            naming:
              implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    thymeleaf:
        cache: false
    session:
        store-type: none
debug: false
trace: false
logging:
    level:
        root: ERROR
        org:
            springframework:
                security: ERROR
                web: ERROR
            hibernate: ERROR
            apache:
                commons:
                    dbcp2: ERROR

